About us
Olga-ampilogova/vyshyvanka-gr19 pull request #7
Opened 2023-10-01 09:58 UTC by Olga-ampilogova

About us section is ready

2023-10-01 11:15 UTC, S-m-i-le requested changes
1. Не зафиксировано положение фонового рисунка.
2. На планшетной версии в классе "about-us-text" margin  должен быть 40px.
3. Нужно ли делать фоновые рисунки для 2х ? Я делал.
4. Согласование отступа с секцией которая выше. Как по мне она должна заканчиваться по линии изображений. Если так, то твоей секции нужен padding-top 80  100 и 150 px соответственно размеру экрана.

2023-10-02 14:53 UTC, Olga-ampilogova commented
> 1. Не зафиксировано положение фонового рисунка.
> 2. На планшетной версии в классе "about-us-text" margin  должен быть 40px.
> 3. Нужно ли делать фоновые рисунки для 2х ? Я делал.
> 4. Согласование отступа с секцией которая выше. Как по мне она должна заканчиваться по линии изображений. Если так, то твоей секции нужен padding-top 80  100 и 150 px соответственно размеру экрана.

All the points are fixed

2023-10-04 19:44 UTC, S-m-i-le approved these changes

2023-10-04 19:46 UTC, S-m-i-le approved these changes

2023-10-04 19:50 UTC, S-m-i-le approved these changes

2023-10-04 19:50 UTC, merged